module Server
  CHECK_CF_CONTEST_HATENA_USER_ID       = ENV['CHECK_CF_CONTEST_HATENA_USER_ID']
  CHECK_CF_CONTEST_HATENA_USER_PASSWORD = ENV['CHECK_CF_CONTEST_HATENA_USER_PASSWORD']
  CHECK_CF_CONTEST_HATENA_GROUP_ID      = ENV['CHECK_CF_CONTEST_HATENA_GROUP_ID']
  CHECK_CF_CONTEST_SECRET_URL           = ENV['CHECK_CF_CONTEST_SECRET_URL']
  CHECK_CF_CONTEST_SECRET_TOKEN         = ENV['CHECK_CF_CONTEST_SECRET_TOKEN']
end
